# Generated by Django 3.2.10 on 2022-01-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='ano',
        ),
    ]
