# Generated by Django 3.2.10 on 2022-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='gv_code',
            field=models.IntegerField(unique=True, verbose_name='GV Code'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='gv_code',
            field=models.IntegerField(unique=True, verbose_name='GV Code'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='gv_code',
            field=models.IntegerField(unique=True, verbose_name='GV Code'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='gv_code',
            field=models.IntegerField(unique=True, verbose_name='GV Code'),
        ),
    ]
