# Generated by Django 3.2.10 on 2022-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='aberta',
            field=models.BooleanField(default=True, verbose_name='Aberta'),
        ),
    ]
