# Generated by Django 3.2.10 on 2022-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0002_vaga_aberta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='cod_vaga',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código'),
        ),
    ]
