# Generated by Django 3.2.10 on 2022-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0003_alter_vaga_cod_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='tempo_experiencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tempo de experiência'),
        ),
    ]
