# Generated by Django 3.2.10 on 2022-05-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0004_alter_vaga_tempo_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='Descrição'),
        ),
    ]
