# Generated by Django 3.2.10 on 2022-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0005_alter_vaga_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='msg_erro_exclusao',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Mens. Erro exclusão'),
        ),
    ]
