# Generated by Django 3.2.10 on 2022-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0006_vaga_msg_erro_exclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fechamento'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_preenchida',
            field=models.DateField(blank=True, null=True, verbose_name='Data Preenchimento'),
        ),
    ]
