# Generated by Django 3.2.10 on 2022-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0007_auto_20220601_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='cidade',
            field=models.CharField(blank=True, default='Canoas', max_length=200, null=True, verbose_name='Cidade'),
        ),
    ]
