# Generated by Django 3.2.10 on 2022-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreiras', '0008_alter_candidatura_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
    ]
