# Generated by Django 3.2.10 on 2022-01-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.IntegerField(verbose_name='Matrícula')),
                ('gv_code', models.IntegerField(verbose_name='GV Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descricao')),
                ('data_evento', models.DateField(verbose_name='Data')),
                ('aluno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.aluno')),
                ('ciclo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciclo')),
                ('curso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('turma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
                ('unidade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enturmacao',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.aluno')),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autorizador',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gv_code', models.IntegerField(verbose_name='GV Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.aluno')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.evento')),
                ('responsavel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.autorizador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
