# Generated by Django 3.2.10 on 2022-01-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('autorizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='autorizacao',
            options={'verbose_name': 'Autorização', 'verbose_name_plural': 'Autorizações'},
        ),
        migrations.AlterModelOptions(
            name='autorizador',
            options={'verbose_name': 'Autorizador', 'verbose_name_plural': 'Autorizadores'},
        ),
        migrations.AlterModelOptions(
            name='enturmacao',
            options={'verbose_name': 'Enturmação', 'verbose_name_plural': 'Enturmações'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='unidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
