# Generated by Django 3.2.10 on 2022-01-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('autorizacoes', '0002_auto_20220121_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='enturmacao',
            name='unidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
