# Generated by Django 3.2.10 on 2022-01-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220124_0933'),
        ('autorizacoes', '0005_auto_20220127_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='unidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
