# Generated by Django 3.2.10 on 2022-01-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220124_0933'),
        ('autorizacoes', '0006_coordenador_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoUnidade',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.evento', verbose_name='Evento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidade', verbose_name='Unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
