# Generated by Django 3.2.10 on 2022-02-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0007_eventounidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacoesModel',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('tipo', models.CharField(default='imagem', max_length=15, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Autorização',
                'verbose_name_plural': 'Tipos de Autorização',
            },
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.autorizacoesmodel', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
