# Generated by Django 3.2.10 on 2022-02-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0008_auto_20220201_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacao',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='AutorizacoesModel',
        ),
    ]
