# Generated by Django 3.2.10 on 2022-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0011_alter_autorizacoesmodel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='termos',
            field=models.TextField(default=0, verbose_name='Termos'),
            preserve_default=False,
        ),
    ]
