# Generated by Django 3.2.10 on 2022-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0012_autorizacao_termos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacoesmodel',
            name='tipo',
            field=models.CharField(default='imagem', max_length=15, unique=True, verbose_name='Tipo'),
        ),
    ]
