# Generated by Django 3.2.10 on 2022-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0013_alter_autorizacoesmodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=1000, verbose_name='Descricao'),
        ),
    ]
