# Generated by Django 3.2.10 on 2022-03-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0014_alter_evento_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTipoAutorizacao',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('data_desativado', models.DateField(blank=True, default=None, null=True, verbose_name='Desativado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_autorizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_autorizacao', to='autorizacoes.autorizacoesmodel', verbose_name='Tipo de Autorização')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
