# Generated by Django 3.2.10 on 2022-03-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0015_eventotipoautorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventotipoautorizacao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.evento', verbose_name='Evento'),
            preserve_default=False,
        ),
    ]
