# Generated by Django 3.2.10 on 2022-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0016_eventotipoautorizacao_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventotipoautorizacao',
            options={'verbose_name': 'Tipo de Autorização do Evento', 'verbose_name_plural': 'Tipos de Autorização do Evento'},
        ),
        migrations.AddField(
            model_name='evento',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data Término'),
        ),
    ]
