# Generated by Django 3.2.10 on 2022-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0017_auto_20220323_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(default='Canoas/RS', max_length=100, verbose_name='Cidade/UF'),
            preserve_default=False,
        ),
    ]
