# Generated by Django 3.2.10 on 2022-03-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220124_0933'),
        ('autorizacoes', '0018_evento_local_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotipoautorizacao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacoes.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventotipoautorizacao',
            name='tipo_autorizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_autorizacao', to='autorizacoes.autorizacoesmodel', verbose_name='Tipo de Autorização'),
        ),
        migrations.AlterField(
            model_name='eventounidade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacoes.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventounidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade', verbose_name='Unidade'),
        ),
    ]
