# Generated by Django 3.2.10 on 2022-03-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0020_alter_evento_data_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacoesmodel',
            name='tipo',
        ),
    ]
