# Generated by Django 3.2.10 on 2022-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0021_remove_autorizacoesmodel_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacoesmodel',
            name='apelido',
            field=models.CharField(default='autorizacao', max_length=15, verbose_name='Apelido'),
            preserve_default=False,
        ),
    ]
