# Generated by Django 3.2.10 on 2022-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0022_autorizacoesmodel_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Cancelamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='msg_erro_cancelamento',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Mens. Erro Cancelamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='obs_cancelamento',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Obs. Cancelamento'),
        ),
    ]
