# Generated by Django 3.2.10 on 2022-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0025_auto_20220411_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='cancelado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='data_revogacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Revogação'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='revogado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Revogado'),
        ),
    ]
