# Generated by Django 3.2.10 on 2022-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0026_auto_20220411_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='autorizacao',
            name='revogado',
            field=models.BooleanField(default=False, verbose_name='Revogado'),
        ),
    ]
