# Generated by Django 3.2.10 on 2022-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0028_alter_autorizacao_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='obs_cancelamento',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Obs. Cancelamento'),
        ),
    ]
