# Generated by Django 3.2.10 on 2022-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0029_autorizacao_obs_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacoesmodel',
            name='gerador',
            field=models.IntegerField(choices=[(1, 'Instituição'), (2, 'Responsável')], default=1, verbose_name='Gerador'),
        ),
    ]
