# Generated by Django 3.2.10 on 2022-06-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0030_autorizacoesmodel_gerador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autorizacoes.evento', verbose_name='Evento'),
        ),
    ]
