# Generated by Django 3.2.10 on 2022-07-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0032_coordenador_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='curso',
        ),
    ]
